{
  ang:{
    tableName:"ang",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      icon:{
        type:"string",
        columnName:"icon"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      varname:{
        type:"string",
        columnName:"varname"
      }
    }
  },
  article:{
    tableName:"article",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      category:{
        type:"integer",
        columnName:"category"
      },
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      copyfrom:{
        type:"string",
        columnName:"copyfrom"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      fromlink:{
        type:"string",
        columnName:"fromlink"
      },
      hits:{
        type:"integer",
        columnName:"hits"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isbold:{
        type:"integer",
        columnName:"isbold"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      puttime:{
        type:"integer",
        columnName:"puttime"
      },
      realhits:{
        type:"integer",
        columnName:"realhits"
      },
      recommends:{
        type:"string",
        columnName:"recommends"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      tags:{
        type:"string",
        columnName:"tags"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpl:{
        type:"string",
        columnName:"tpl"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      }
    }
  },
  ask:{
    tableName:"ask",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      category:{
        type:"integer",
        columnName:"category"
      },
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      hits:{
        type:"integer",
        columnName:"hits"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isbold:{
        type:"integer",
        columnName:"isbold"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      puttime:{
        type:"integer",
        columnName:"puttime"
      },
      realhits:{
        type:"integer",
        columnName:"realhits"
      },
      recommends:{
        type:"string",
        columnName:"recommends"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      tags:{
        type:"string",
        columnName:"tags"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpl:{
        type:"string",
        columnName:"tpl"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      }
    }
  },
  category:{
    tableName:"category",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      description:{
        type:"string",
        columnName:"description"
      },
      dir:{
        type:"string",
        columnName:"dir"
      },
      externalurl:{
        type:"string",
        columnName:"externalurl"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isdisabled:{
        type:"integer",
        columnName:"isdisabled"
      },
      isexternal:{
        type:"integer",
        columnName:"isexternal"
      },
      isnavigation:{
        type:"integer",
        columnName:"isnavigation"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      lft:{
        type:"integer",
        columnName:"lft"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      model:{
        type:"string",
        columnName:"model"
      },
      name:{
        type:"string",
        columnName:"name"
      },
      pagesize:{
        type:"integer",
        columnName:"pagesize"
      },
      parent:{
        type:"integer",
        columnName:"parent"
      },
      rht:{
        type:"integer",
        columnName:"rht"
      },
      target:{
        type:"string",
        columnName:"target"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpldetail:{
        type:"string",
        columnName:"tpldetail"
      },
      tpllist:{
        type:"string",
        columnName:"tpllist"
      }
    }
  },
  config:{
    tableName:"config",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      category:{
        type:"string",
        columnName:"category"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      issystem:{
        type:"integer",
        columnName:"issystem"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      value:{
        type:"text",
        columnName:"value"
      },
      varname:{
        type:"string",
        columnName:"varname"
      }
    }
  },
  down:{
    tableName:"down",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      attrname:{
        type:"string",
        columnName:"attrname"
      },
      attrurl:{
        type:"string",
        columnName:"attrurl"
      },
      category:{
        type:"integer",
        columnName:"category"
      },
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      hits:{
        type:"integer",
        columnName:"hits"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isbold:{
        type:"integer",
        columnName:"isbold"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      puttime:{
        type:"integer",
        columnName:"puttime"
      },
      realhits:{
        type:"integer",
        columnName:"realhits"
      },
      recommends:{
        type:"string",
        columnName:"recommends"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      tags:{
        type:"string",
        columnName:"tags"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpl:{
        type:"string",
        columnName:"tpl"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      }
    }
  },
  fragment:{
    tableName:"fragment",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      remark:{
        type:"text",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      },
      varname:{
        type:"string",
        columnName:"varname"
      }
    }
  },
  guestbook:{
    tableName:"guestbook",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      author:{
        type:"string",
        columnName:"author"
      },
      category:{
        type:"integer",
        columnName:"category"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      email:{
        type:"string",
        columnName:"email"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      phone:{
        type:"string",
        columnName:"phone"
      },
      replytime:{
        type:"integer",
        columnName:"replytime"
      },
      replyuid:{
        type:"integer",
        columnName:"replyuid"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      }
    }
  },
  hr:{
    tableName:"hr",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      category:{
        type:"integer",
        columnName:"category"
      },
      city:{
        type:"string",
        columnName:"city"
      },
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      hits:{
        type:"integer",
        columnName:"hits"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isbold:{
        type:"integer",
        columnName:"isbold"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      num:{
        type:"string",
        columnName:"num"
      },
      puttime:{
        type:"integer",
        columnName:"puttime"
      },
      realhits:{
        type:"integer",
        columnName:"realhits"
      },
      recommends:{
        type:"string",
        columnName:"recommends"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      tags:{
        type:"string",
        columnName:"tags"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpl:{
        type:"string",
        columnName:"tpl"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      },
      year:{
        type:"string",
        columnName:"year"
      }
    }
  },
  keywords:{
    tableName:"keywords",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      url:{
        type:"string",
        columnName:"url"
      }
    }
  },
  link:{
    tableName:"link",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      remark:{
        type:"text",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      type:{
        type:"integer",
        columnName:"type"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      },
      url:{
        type:"string",
        columnName:"url"
      }
    }
  },
  login:{
    tableName:"login",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      createdAt:{
        type:"",
        columnName:"createdAt"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      updatedAt:{
        type:"",
        columnName:"updatedAt"
      }
    }
  },
  model:{
    tableName:"model",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      id:{
        type:"integer",
        columnName:"id"
      },
      isrecommend:{
        type:"integer",
        columnName:"isrecommend"
      },
      issearch:{
        type:"integer",
        columnName:"issearch"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      varname:{
        type:"string",
        columnName:"varname"
      }
    }
  },
  navigation:{
    tableName:"navigation",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      color:{
        type:"string",
        columnName:"color"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      rel:{
        type:"string",
        columnName:"rel"
      },
      remark:{
        type:"string",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      type:{
        type:"integer",
        columnName:"type"
      },
      url:{
        type:"string",
        columnName:"url"
      }
    }
  },
  online:{
    tableName:"online",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      description:{
        type:"text",
        columnName:"description"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      remark:{
        type:"text",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      type:{
        type:"string",
        columnName:"type"
      }
    }
  },
  page:{
    tableName:"page",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      createdAt:{
        type:"",
        columnName:"createdAt"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      updatedAt:{
        type:"",
        columnName:"updatedAt"
      }
    }
  },
  product:{
    tableName:"product",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      category:{
        type:"integer",
        columnName:"category"
      },
      color:{
        type:"string",
        columnName:"color"
      },
      content:{
        type:"text",
        columnName:"content"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      hits:{
        type:"integer",
        columnName:"hits"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      isbold:{
        type:"integer",
        columnName:"isbold"
      },
      keywords:{
        type:"string",
        columnName:"keywords"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      price:{
        type:"float",
        columnName:"price"
      },
      puttime:{
        type:"integer",
        columnName:"puttime"
      },
      realhits:{
        type:"integer",
        columnName:"realhits"
      },
      recommends:{
        type:"string",
        columnName:"recommends"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      tags:{
        type:"string",
        columnName:"tags"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      tpl:{
        type:"string",
        columnName:"tpl"
      },
      uid:{
        type:"integer",
        columnName:"uid"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      }
    }
  },
  purview:{
    tableName:"purview",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      class:{
        type:"string",
        columnName:"class"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      method:{
        type:"string",
        columnName:"method"
      },
      parent:{
        type:"integer",
        columnName:"parent"
      },
      status:{
        type:"integer",
        columnName:"status"
      }
    }
  },
  recommend:{
    tableName:"recommend",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      model:{
        type:"string",
        columnName:"model"
      },
      remark:{
        type:"text",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      }
    }
  },
  sessions:{
    tableName:"sessions",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      ip_address:{
        type:"string",
        columnName:"ip_address"
      },
      last_activity:{
        type:"integer",
        columnName:"last_activity"
      },
      session_id:{
        type:"string",
        columnName:"session_id"
      },
      user_agent:{
        type:"string",
        columnName:"user_agent"
      },
      user_data:{
        type:"text",
        columnName:"user_data"
      }
    }
  },
  slide:{
    tableName:"slide",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      description:{
        type:"text",
        columnName:"description"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      remark:{
        type:"text",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      type:{
        type:"integer",
        columnName:"type"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      },
      url:{
        type:"string",
        columnName:"url"
      }
    }
  },
  tags:{
    tableName:"tags",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      url:{
        type:"string",
        columnName:"url"
      }
    }
  },
  tpltags:{
    tableName:"tpltags",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      description:{
        type:"text",
        columnName:"description"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      title:{
        type:"string",
        columnName:"title"
      },
      type:{
        type:"string",
        columnName:"type"
      },
      value:{
        type:"text",
        columnName:"value"
      }
    }
  },
  type:{
    tableName:"type",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      class:{
        type:"string",
        columnName:"class"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      lang:{
        type:"string",
        columnName:"lang"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      remark:{
        type:"string",
        columnName:"remark"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      thumb:{
        type:"string",
        columnName:"thumb"
      },
      title:{
        type:"string",
        columnName:"title"
      }
    }
  },
  user:{
    tableName:"user",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      address:{
        type:"string",
        columnName:"address"
      },
      Alter_priv:{
        type:"",
        columnName:"Alter_priv"
      },
      Alter_routine_priv:{
        type:"",
        columnName:"Alter_routine_priv"
      },
      authentication_string:{
        type:"text",
        columnName:"authentication_string"
      },
      createtime:{
        type:"integer",
        columnName:"createtime"
      },
      Create_priv:{
        type:"",
        columnName:"Create_priv"
      },
      Create_routine_priv:{
        type:"",
        columnName:"Create_routine_priv"
      },
      Create_tablespace_priv:{
        type:"",
        columnName:"Create_tablespace_priv"
      },
      Create_tmp_table_priv:{
        type:"",
        columnName:"Create_tmp_table_priv"
      },
      Create_user_priv:{
        type:"",
        columnName:"Create_user_priv"
      },
      Create_view_priv:{
        type:"",
        columnName:"Create_view_priv"
      },
      Delete_priv:{
        type:"",
        columnName:"Delete_priv"
      },
      Drop_priv:{
        type:"",
        columnName:"Drop_priv"
      },
      email:{
        type:"string",
        columnName:"email"
      },
      Event_priv:{
        type:"",
        columnName:"Event_priv"
      },
      Execute_priv:{
        type:"",
        columnName:"Execute_priv"
      },
      fax:{
        type:"string",
        columnName:"fax"
      },
      File_priv:{
        type:"",
        columnName:"File_priv"
      },
      Grant_priv:{
        type:"",
        columnName:"Grant_priv"
      },
      Host:{
        type:"string",
        columnName:"Host"
      },
      id:{
        type:"integer",
        columnName:"id"
      },
      Index_priv:{
        type:"",
        columnName:"Index_priv"
      },
      Insert_priv:{
        type:"",
        columnName:"Insert_priv"
      },
      lastip:{
        type:"string",
        columnName:"lastip"
      },
      lasttime:{
        type:"integer",
        columnName:"lasttime"
      },
      Lock_tables_priv:{
        type:"",
        columnName:"Lock_tables_priv"
      },
      logincount:{
        type:"integer",
        columnName:"logincount"
      },
      max_connections:{
        type:"integer",
        columnName:"max_connections"
      },
      max_questions:{
        type:"integer",
        columnName:"max_questions"
      },
      max_updates:{
        type:"integer",
        columnName:"max_updates"
      },
      max_user_connections:{
        type:"integer",
        columnName:"max_user_connections"
      },
      mobile:{
        type:"string",
        columnName:"mobile"
      },
      name:{
        type:"string",
        columnName:"name"
      },
      password:{
        type:"string",
        columnName:"password"
      },
      Password:{
        type:"string",
        columnName:"Password"
      },
      plugin:{
        type:"string",
        columnName:"plugin"
      },
      Process_priv:{
        type:"",
        columnName:"Process_priv"
      },
      realname:{
        type:"string",
        columnName:"realname"
      },
      References_priv:{
        type:"",
        columnName:"References_priv"
      },
      regip:{
        type:"string",
        columnName:"regip"
      },
      Reload_priv:{
        type:"",
        columnName:"Reload_priv"
      },
      Repl_client_priv:{
        type:"",
        columnName:"Repl_client_priv"
      },
      Repl_slave_priv:{
        type:"",
        columnName:"Repl_slave_priv"
      },
      salt:{
        type:"string",
        columnName:"salt"
      },
      Select_priv:{
        type:"",
        columnName:"Select_priv"
      },
      sex:{
        type:"integer",
        columnName:"sex"
      },
      Show_db_priv:{
        type:"",
        columnName:"Show_db_priv"
      },
      Show_view_priv:{
        type:"",
        columnName:"Show_view_priv"
      },
      Shutdown_priv:{
        type:"",
        columnName:"Shutdown_priv"
      },
      ssl_cipher:{
        type:"",
        columnName:"ssl_cipher"
      },
      ssl_type:{
        type:"",
        columnName:"ssl_type"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      Super_priv:{
        type:"",
        columnName:"Super_priv"
      },
      tel:{
        type:"string",
        columnName:"tel"
      },
      Trigger_priv:{
        type:"",
        columnName:"Trigger_priv"
      },
      updatetime:{
        type:"integer",
        columnName:"updatetime"
      },
      Update_priv:{
        type:"",
        columnName:"Update_priv"
      },
      User:{
        type:"string",
        columnName:"User"
      },
      usergroup:{
        type:"integer",
        columnName:"usergroup"
      },
      username:{
        type:"string",
        columnName:"username"
      },
      x509_issuer:{
        type:"",
        columnName:"x509_issuer"
      },
      x509_subject:{
        type:"",
        columnName:"x509_subject"
      }
    }
  },
  usergroup:{
    tableName:"usergroup",
    autoCreatedAt:false,
    autoUpdatedAt:false,
    attributes:{
      id:{
        type:"integer",
        columnName:"id"
      },
      isupdate:{
        type:"integer",
        columnName:"isupdate"
      },
      listorder:{
        type:"integer",
        columnName:"listorder"
      },
      purview:{
        type:"text",
        columnName:"purview"
      },
      status:{
        type:"integer",
        columnName:"status"
      },
      varname:{
        type:"string",
        columnName:"varname"
      }
    }
  }
}